controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

chatbot:
    path: /chatbot
    controller: App\Controller\ChatbotController::index

