<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFG5eGxu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFG5eGxu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFG5eGxu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFG5eGxu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFG5eGxu\App_KernelDevDebugContainer([
    'container.build_hash' => 'FG5eGxu',
    'container.build_id' => '20436349',
    'container.build_time' => 1720796369,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFG5eGxu');
