<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJZ1Do3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJZ1Do3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJZ1Do3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJZ1Do3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQJZ1Do3\App_KernelDevDebugContainer([
    'container.build_hash' => 'QJZ1Do3',
    'container.build_id' => '4765c216',
    'container.build_time' => 1720605759,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJZ1Do3');
