<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUEfNfAk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUEfNfAk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUEfNfAk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUEfNfAk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUEfNfAk\App_KernelDevDebugContainer([
    'container.build_hash' => 'UEfNfAk',
    'container.build_id' => 'd57854b8',
    'container.build_time' => 1720708649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUEfNfAk');
